# Generated by Django 4.1.7 on 2023-06-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='brochure.category'),
        ),
    ]
