version: "3"

services:
  api:
    build: ./backend/api
    ports:
      - "8790:8790"
    volumes:
      - ./volumes/api:/code
    environment:
      - DEBUG=1
 
  client:
      build: ./prezzo
      ports:
        - "3000:3000"
      volumes: 
        - ./volumes/client:/client
      environment:
        - DEBUG=1
 

 